### ISSUE TITLE
Include Webpack4

### ISSUE THREAD

**Issue by developer-lindner** [GoogleChromeLabs/webpack-training-project#4]
Due to recent release of Webpack4 some things changed. Is there any update planned?

**Comment by iamakulov** [comment]
Sure! The reason we’re not updating this yet is that some plugins (e.g., `HtmlWebpackPlugin`) are not ready for webpack 4 yet. I believe this would get updated in a week or two.

**Comment by iamakulov** [comment]
Done in #5! Thank you for your patience :–)
